"""Storage protocol — interface for all storage backends."""

from __future__ import annotations

from typing import Any, Protocol

from parawave.storage.models import ItemRecord, RunInfo, RunRecord
from parawave.result import Result


class Storage(Protocol):
    """Protocol that all storage backends must implement."""

    async def create_run(
        self, run_id: str, config: dict, func_hash: str, items: list[dict],
        tags: dict[str, str] | None = None,
        func_name: str = "",
    ) -> None: ...

    async def get_run(self, run_id: str) -> RunRecord: ...

    async def run_exists(self, run_id: str) -> bool: ...

    async def update_item_status(
        self, run_id: str, index: int, status: str, error: str | None,
        attempts: int = 1, elapsed: float = 0.0,
    ) -> None: ...

    async def get_items_by_status(
        self, run_id: str, status: str
    ) -> list[ItemRecord]: ...

    async def get_all_items(self, run_id: str) -> list[ItemRecord]: ...

    async def save_item_output(
        self, run_id: str, index: int, output: Any
    ) -> None: ...

    async def load_item_output(self, run_id: str, index: int) -> Any: ...

    async def load_item_input(self, run_id: str, index: int) -> dict: ...

    async def get_item_input_hash(self, run_id: str, index: int) -> str: ...

    async def update_run_config(self, run_id: str, config: dict) -> None: ...

    async def close(self) -> None: ...

    # Management methods
    async def list_runs(self, tags: dict[str, str] | None = None, status: str | None = None) -> list[RunInfo]: ...

    async def get_run_info(self, run_id: str) -> RunInfo: ...

    async def load_result(self, run_id: str) -> Result: ...

    async def update_tags(self, run_id: str, tags: dict[str, str]) -> None: ...

    async def delete_run(self, run_id: str) -> None: ...

    # Execution support methods
    async def update_run_status(self, run_id: str, status: str) -> None: ...

    async def update_run_elapsed(self, run_id: str, elapsed: float) -> None: ...

    async def get_run_elapsed(self, run_id: str) -> float: ...
